name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Install popf deps
        run: sudo apt-get install libfl-dev
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: foxy
      - name: build and test
        uses: fmrico/action-ros-ci@0.1.1
        with:
          package-name: mylib myapp
          target-ros2-distro: foxy
          vcs-repo-file-url: ""
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: false
